config/routes.rb
BootstrapApp::Application.routes.draw do
  
  
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users, :controllers => {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  root :to => "welcome#index"
  get "welcome/index"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "APP NAME", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
  <% if user_signed_in? %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <% if current_user.has_role? :admin %>
      <li><%= link_to 'Admin', users_path %></li>
    <% end %>
  <% else %>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
  <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bootstrap App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "APP NAME" %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <% if user_signed_in? %>
    	<%= render 'navigation/sticky' %>
    <% end %>
    
    <header class="navbar navbar-fixed-top">
      <nav class="navbar navbar-default" role="navigation">
          <%= render 'layouts/navigation' %>
      </nav>
    </header>
   
    <div id="main" role="main">
      <div class="container">
           	<div class="row">
            	<div class="span12">
              		<%= render 'layouts/messages' %>
              		<%= yield %>
            	</div>
           	</div>
          	<footer>
          	
          	</footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>